title: CS 533 Fall 2022
author: Michael D. Ekstrand
copyright: '2020â€“2022'
# logo: logo.png

exclude_patterns:
- .venv/*
- venv/*
- node_modules/*
- README.md
- assignments/A0/A0-Solution.ipynb

# bibtex_bibfiles:
  # - references.bib

repository:
  url: https://github.com/mdekstrand/cs533-web
  branch: main

parse:
  myst_heading_anchors: 2
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution
  myst_substitutions:
    moverview: ğŸ§
    mcal: ğŸ“…
    mvideo: ğŸ¥
    mbook: ğŸ“–
    mdoc: ğŸ“ƒ
    mclass: ğŸ‘¨â€ğŸ«
    mnotebook: ğŸ““
    mnote: ğŸ“
    massignment: ğŸ“©
    mtask: âœ…
    mtodo: âœ…
    mquiz: ğŸš©
    mdownload: ğŸŒ 
    LMS: Canvas

execute:
  execute_notebooks: 'off'
  exclude_patterns:
  - assignments/*/*.ipynb
  - resources/tutorials/*.ipynb

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  favicon: logo.png
  extra_footer: |
    <script data-goatcounter="https://cs533.goatcounter.com/count"
            async src="//gc.zgo.at/count.js"></script>
  comments:
    utterances:
      repo: mdekstrand/cs533-web

launch_buttons:
  binderhub_url: ''

sphinx:
  local_extensions:
    admonitions: extensions
    media: extensions
    cleanups: extensions
    schedule: extensions
  config:
    primary_domain: res
    term: F22
    course_start: 2022-08-22
    break_week: 14
    external_toc_exclude_missing: true
    mathjax3_config:
      tex:
        macros:
          E: "\\mathrm{E}"
          Field: "\\mathcal{F}"
          P: "\\mathrm{P}"
          Cov: "\\mathrm{Cov}"
          Cor: "\\mathrm{Cor}"
          Var: "\\mathrm{Var}"
          log: "\\operatorname{log}"
          Odds: "\\operatorname{Odds}"
          OR: "\\operatorname{OR}"
          IND: "\\mathbb{I}"
          Reals: "\\mathbb{R}"
      HTML-CSS:
        fonts: ["TeX"]
    intersphinx_mapping:
      python: [https://docs.python.org/3, null]
      numpy: [https://numpy.org/doc/stable/, null]
      scipy: [https://docs.scipy.org/doc/scipy/reference/, null]
      pandas: [https://pandas.pydata.org/docs/, null]
      seaborn: [https://seaborn.pydata.org/, null]
      matplotlib: [https://matplotlib.org/, null]
      sklearn: [https://scikit-learn.org/stable/, null]
      statsmodels: [https://www.statsmodels.org/stable/, null]
      seedbank: [https://seedbank.lenskit.org/en/stable, null]
    docs_versions_menu_conf:
      json_file: '/versions.json'
