title: CS 533 Fall 2021
author: Michael D. Ekstrand
copyright: '2021'
# logo: logo.png

# bibtex_bibfiles:
  # - references.bib

repository:
  url: https://github.com/mdekstrand/cs533-web
  branch: main

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution
  myst_substitutions:
    mcal: ğŸ“…
    mvideo: ğŸ¥
    mbook: ğŸ“–
    mclass: ğŸ‘¨â€ğŸ«
    mnotebook: ğŸ“
    massignment: ğŸ“©
    mtask: âœ…
    mquiz: ğŸš©

execute:
  exclude_patterns:
  - assignments/*/*.ipynb
  - resources/tutorials/*.ipynb

html:
  use_issues_button: true
  use_repository_button: true
  favicon: logo.png

launch_buttons:
  binderhub_url: ''

sphinx:
  local_extensions:
    admonitions: extensions
    media: extensions
  config:
    primary_domain: res
    mathjax_config:
      TeX:
        Macros:
          E: "\\mathrm{E}"
          F: "\\mathcal{F}"
          P: "P"
          Cov: "\\mathrm{Cov}"
          Var: "\\mathrm{Var}"
          log: "\\operatorname{log}"
          Odds: "\\operatorname{Odds}"
          OR: "\\operatorname{OR}"
          IND: "\\mathbb{I}"
          Reals: "\\mathbb{R}"
