name: Publish Site
on:
  push:
    branches:
      - main
      - archive

jobs:
  publish:
    name: Publish Site
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
    - name: â¬ Check out source code
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

    - name: Set up software
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: conda-lock.yml
        environment-name: cs533
        generate-run-shell: true

    - name: ğŸŒ¿ Prepare Git branch
      run: |
        git branch archive origin/archive

    - name: ğŸ›  Build site
      run: |
        jb --version
        invoke build-site
      shell: micromamba-shell {0}

    - name: ğŸ“¢ Publish
      run: |
        go run github.com/mdekstrand/deploy-to-netlify@latest -d _build/site
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
