name: Publish Site
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Site
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
    - name: â¬ Check out source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: ğŸ Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: ğŸ•¸ Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: ğŸ’° Cache package caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.cache/pip
        key: pkg-cache-cache

    - name: ğŸ“¦ Install pipenv packages
      run: |
        python -m pip install pipenv

    - name: ğŸ’° Cache Python environment
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-py38-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-py38-

    - name: ğŸ“ Install Python dependencies
      run: |
        pipenv install --deploy
    
    - name: ğŸ“ Install Node dependencies
      run: |
        npm ci

    - name: ğŸ›  Build site
      run: |
        npm run build
    
    - name: ğŸ“¢ Publish
      run: |
        netlify deploy --dir=full-site --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
