name: Publish Site
on:
  push:
    branches:
      - main
      - archive

jobs:
  publish:
    name: Publish Site
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
    - name: â¬ Check out source code
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0

    - name: ğŸ Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: ğŸ’° Cache Python environment
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-py310-${{ hashFiles('requirements.txt') }}

    - name: ğŸ“¦ Set up virtual environment
      run: |
        python -m venv venv
        ./venv/bin/pip install wheel
        echo "$PWD/venv/bin" >>$GITHUB_PATH

    - name: ğŸ“ Install Python dependencies
      run: |
        echo "PATH=$PATH"
        which pip
        pip install -r requirements.txt

    - name: ğŸŒ¿ Prepare Git branch
      run: |
        git branch archive origin/archive

    - name: ğŸ›  Build site
      run: |
        jb --version
        invoke build-site

    - name: ğŸ“¢ Publish
      run: |
        go run github.com/mdekstrand/deploy-to-netlify@latest -d _build/site
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
